### PR TITLE
fix: fix >150mb bodies from crashing

### PR DESCRIPTION
**Pull request by hugomrdias**
This PR fixes lots of problems with large http bodies 

Related
https://github.com/ipfs/js-ipfs-api/issues/654
https://github.com/ipfs/js-ipfs-api/issues/788
https://github.com/ipfs/js-ipfs-api/issues/788
just to reference a few we have lots of these.

### CODE REVIEW

**Comment by diasdavid** [comment]
Ping @jhiesey :)

**Comment by jhiesey** [comment]
I think this looks fine. This won't work in IE10, but I think it's time to stop supporting that anyway.

I'm going to go in and rip out older IE support, then release this as a new major version.

**Comment by jhiesey** [comment]
So this is merged, but I want to wait to release v3.0.0 until https://github.com/nodejs/readable-stream/issues/364 is fixed

**Comment by jhiesey** [comment]
Released as v3.0.0

**Pull request merged**
