### PR TITLE
Adding support for Service Workers.

### PR DESCRIPTION
**Pull request by mikeal**
For some reason Service Workers have `fetch` but not `XMLHttpRequest`. This fixes it.

### CODE REVIEW

**Comment by jhiesey** [comment]
Thanks!

**Comment by jhiesey** [comment]
The localtunnel server is failing right now, but as soon as I can run the tests I'll release a new patch version.

**Comment by mikeal** [comment]
Awesome, thanks. Some time after that I'll need to poke substack to update browserify's dep with the new version.

**Comment by xuset** [comment]
@jhiesey the localtunnels seems to fail every now and then for me too. When do you think you'll have the time to run the tests and release a new version?

**Pull request merged**
