### PR TITLE
Replaces symbol iterator with foreach function

### PR DESCRIPTION
**Pull request by ecoslado**

### CODE REVIEW

**Comment by ecoslado** [comment]
This PR is related with issue #48

**Comment by gillstrom** [comment]
Any chance this could get merged in the near future?

**Comment by alonalon** [comment]
@jhiesey would be really helpful if you could merge this!

**Comment by jhiesey** [comment]
Looks great! Sorry for the slow response; I've been busy on other projects recently.

**Comment by gillstrom** [comment]
Thanks @jhiesey and @ecoslado. Any chance for a new release to npm?

**Comment by jhiesey** [comment]
Released as v2.4.1

**Pull request merged**
