### PR TITLE
Add http methods from node v0.12

### LINKED ISSUE #10: http.METHODS is missing PATCH and others
Hello @jhiesey,

I noticed after upgrading to `browserify@11.0.1`. Our team specifically noticed `require('http').METHODS` was missing `'PATCH'`. Is there any reason why this is hardcoded to https://github.com/jhiesey/stream-http/blob/master/index.js#L51? If not can you please add `'PATCH'` and others to this list maybe you can use https://www.npmjs.com/package/methods?

### PR DESCRIPTION
**Pull request by tjmehta**
Fixes #10

### CODE REVIEW

**Comment by feross** [comment]
This project uses tabs instead of two spaces. Can you update your PR?

**Comment by tjmehta** [comment]
sure, give me a few

**Comment by tjmehta** [comment]
done

**Comment by tjmehta** [comment]
Whoops, looks like my editor was replacing tabs with spaces.
Fixed for real now.

**Comment by jhiesey** [comment]
Thanks!

**Pull request merged**
